# Generated by Django 2.1.5 on 2019-01-20 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=512)),
                ('hardcover', models.NullBooleanField()),
                ('want', models.BooleanField()),
                ('version', models.CharField(max_length=128)),
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('sold', models.BooleanField()),
                ('poster', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('poster', models.EmailField(max_length=254)),
                ('buyer', models.EmailField(max_length=254)),
                ('time', models.DateTimeField()),
                ('text', models.TextField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Book')),
            ],
        ),
    ]
